### ISSUE TITLE
Extra parameter requirements in POST /user/users

### ISSUE THREAD

**Issue by shazelquist** [cpsc462/microsocial#74]
Pull request #72 overwrites the definitions for `CreatingUser` in `/user` [here](https://github.com/cpsc462/microsocial/blob/2a0c8da7cfe7fd75fb10de143cf1fbafce50e66c/analytics/swaggerdefs.js#L160).

I think analytics may have forgotten to change the object name in their swaggerdefs, so they should probably change that to something unique so it doesn't overwrite the `/user` definition.

**Comment by vudiep411** [comment]
fixed in #72

**Comment by shazelquist** [comment]
@vudiep411 This has not been resolved and should not be closed. #72 Is where the issue started, and the issue is still live. 

``CreatingUser`` in /user [here](https://github.com/cpsc462/microsocial/blob/ec161bfdbbdfcc6e8ffd45a44373c03cd6dd701c/user/swaggerdefs.js#L132)
Erroneous redefinition of ``CreatingUser`` in /analytics [here](https://github.com/cpsc462/microsocial/blob/ec161bfdbbdfcc6e8ffd45a44373c03cd6dd701c/analytics/swaggerdefs.js#L160)
